services:
  - type: web
    name: i-intern-backend
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      # Core application settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      
      # CORS and URL configuration
      - key: ALLOWED_ORIGINS
        value: https://i-intern-2.onrender.com,https://i-intern.com,https://www.i-intern.com
      - key: FRONTEND_URL
        value: https://i-intern-2.onrender.com
      - key: BACKEND_URL
        value: https://i-intern.onrender.com
      
      # Cookie configuration (required for secure authentication)
      - key: COOKIE_SAMESITE
        value: lax
      - key: COOKIE_SECURE
        value: true
      - key: COOKIE_DOMAIN
        # Using Render subdomains in production; set cookie domain to the Render parent
        # so cookies are available across Render-hosted subdomains (e.g. i-intern-2.onrender.com).
        value: .onrender.com
      - key: COOKIE_HTTPONLY
        value: true
      - key: COOKIE_MAX_AGE
        value: 604800
      
      # Email/SMTP configuration (required for password reset and email verification)
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false  # Set in Render dashboard - your Gmail address
      - key: SMTP_PASSWORD
        sync: false  # Set in Render dashboard - Gmail App Password (not regular password)
      - key: FROM_EMAIL
        sync: false  # Set in Render dashboard - sender email address
      
      # Google OAuth (optional - currently disabled in code)
      # Uncomment and configure if you want to enable Google login
      # - key: GOOGLE_CLIENT_ID
      #   sync: false
      # - key: GOOGLE_CLIENT_SECRET
      #   sync: false
      
      # Build configuration for Rust dependencies (WeasyPrint)
      - key: CARGO_HOME
        value: /opt/render/project/.cargo
      - key: CARGO_TARGET_DIR
        value: /opt/render/project/.cargo-target

